export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_MOVIES = "GET_USER_MOVIES";
export const SET_CURRENT_ROOM = "SET_CURRENT_ROOM";
export const SET_CURRENT_MOVIE = "SET_CURRENT_MOVIE";
